[build]
  # Satisfies the npm run build command, which must exist.
  command = "echo 'No static build needed.'" 

  # Set publish directory to the repository root since your files (index.html, script.js) are there.
  publish = "." 
  
  # Directory where Netlify will look for and build your serverless functions.
  functions = "netlify/functions"
