[build]
  # This command installs 'node-fetch' and runs your dummy build script.
  command = "npm install && npm run build" 
  
  # Sets the publish directory to the root where index.html is located.
  publish = "." 
  
  # Directory where Netlify finds your serverless functions.
  functions = "netlify/functions"

[functions]
  # Ensures the function is bundled correctly.
  node_bundler = "esbuild"
