[build]
  # Uses the dummy script added in package.json
  command = "npm run build"
  
  # Tells Netlify to serve files from the root directory
  publish = "." 
  
  # Confirms where your Netlify Function (gemini-proxy.js) is located
  functions = "netlify/functions"
