[build]
  # We still use 'npm run build' because we added a dummy script in package.json
  command = "npm run build"
  
  # Set publish directory to the repository root since index.html is here
  publish = "." 
  
  # Directory where Netlify finds your serverless functions
  functions = "netlify/functions"
